### PR TITLE
Upstream catchup 202304

### PR DESCRIPTION
**Pull request by danrademacher**
This pulls in the latest upstream for iD using `git merge upstream/release -Xours`. There are no merge conflicts here, but currently, this is not working for the simple reason that there's a new `.env` file needed:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'dotenv' imported from /Users/danrademacher/Documents/GINlocalcode/OHM-iD/config/envs.mjs
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

This new file, https://github.com/OpenHistoricalMap/iD/blob/upstream-catchup-202304/config/envs.mjs, is where we need to sort out what all these ENVs need to be, then we can see how well things work after that...

### CODE REVIEW

**Comment by danrademacher** [comment]
@1ec5 do you have any tips on the new `.env` values required for iD? I thought there might be a sample file or list of definitions in the README, but neither jumped out at me in latest upstream.

Looks like we need to define all these to run locally:
```
ID_PRESETS_CDN_URL
ID_OCI_CDN_URL
ID_NSI_CDN_URL
ID_WMF_SITEMATRIX_CDN_URL
ID_API_CONNECTION_URL
ID_API_CONNECTION_CLIENT_ID
ID_API_CONNECTION_CLIENT_SECRET
ID_API_CONNECTION
ENV__ID_TAGINFO_API_URL
ENV__ID_NOMINATIM_API_URL
```

Some I know for OHM, others we never changed so probably defaulted to whatever was, I assume, hard-coded in previous versions of iD.

**Comment by danrademacher** [comment]
@geohacker this is where I started the iD catch-up

**Comment by 1ec5** [comment]
Check out each of the commits listed in [the envs.mjs file history](https://github.com/openstreetmap/iD/commits/a15f6ff338dd7b1a1e64b90574afba0d67be96ce/config/envs.mjs), which show what the variables replaced. It looks like the fork is currently setting these configuration variables in [id.js](https://github.com/OpenHistoricalMap/iD/blob/9aaf00193618da3ae6ef760e84c03e27065d58e7/config/id.js). Setting them to what was previously in id.js should be OK for now, although some of them eventually need to be customized for OpenHistoricalMap: OpenHistoricalMap/issues#432.

/ref https://github.com/OpenHistoricalMap/iD/pull/148#pullrequestreview-1144841080

**Comment by danrademacher** [comment]
Closed in favor of new work from @erictheise

**Pull request closed without merging**
